#!/usr/bin/env python3
"""
mutt-open is a wrapper around xdg-open, created for use
with mutt/mailcap. The main difference between mutt-open
and xdg-open is that mutt-open creates a copy of the file
that is being opened before calling xdg-open.

Usage: mutt-open <filename> [sufix]

* <filename> is the name of the file to be opened
* [suffix] is an optional suffix to be added to the new file
  name, e.g. a file extension

"""

import tempfile
from shutil import copyfile
import sys, os
from subprocess import call
from hashlib import sha1

def file_sha1(path, block_size=2**20):
    f = open(path, 'rb')
    h = sha1()
    while True:
        data = f.read(block_size)
        if not data:
            break
        h.update(data)

    f.close()
    return h.hexdigest()

if __name__ == '__main__':

    if len(sys.argv) < 2:
        print('Usage: %s <filename> [suffix]')
        sys.exit(-1)

    oldfile = sys.argv[1]

    suffix = os.path.basename(oldfile)
    if True: # FIXME: add an option to enable/disable this
        suffix = file_sha1(oldfile) + suffix

    if len(sys.argv) == 3:
        suffix += sys.argv[2]

    newfile = os.path.join(tempfile.gettempdir(), 'mutt_bak_' + suffix)

    copyfile(oldfile, newfile)
    call(['xdg-open', newfile])



